name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - build-context/*
      - .github/workflows/dockerimage.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./build-context
          file: ./build-context/Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: |
            wagoautomation/docker-compose:${{ steps.tag_version.outputs.new_tag }}
            wagoautomation/docker-compose:latest
